app:
  rabbitmq:
    exchange: employeeexchange
    queue: employeequeue
    routingkey: employeeroutingkey
  message: Message sent to the RabbitMQ queue Successfully
spring:
  rabbitmq:
    #add the rabbitmq headless service name as host
    host:
    #add the username and password from secret. For example: ${<environment variable name>}
    username:
    password:
    port: 5672
server:
  port: 9090
